### PR TITLE
Improve connect interface

### PR DESCRIPTION
**Pull request by philbucher**
**!!! THIS IS AN IMPORTANT CHANGE !!!**

Currently the codes connecting to CoSimIO have to set `connection_name` in the `CoSimIO::Info` when calling any function from `CoSimIO`

The problem is that this is not intuitive from the user point of view and it gives some serious technical problems (esp in determining who is the "leader" of the connection, i.e. who opens Sockert/MPI-ports, creates communication-folders etc)

I am proposing to change to the following (we already discussed this)
~~~c++
CoSimIO::Info settings;
settings.Set("name", "export_solver");
settings.Set("connect_to", "import_solver");

auto info = CoSimIO::Connect(settings);
const std::string connection_name = info.Get<std::string>("connection_name");
// use "connection_name" as before for the following function calls
~~~

NOTE: This ofc will require to update the tutorials too. I only did one test so far to illustrate the change. After we agreed I will update the rest

### CODE REVIEW

**Comment by pooyan-dadvand** [comment]
I agree. The only minor thing is the `"name"` label which I'm not sure if is very clear. (vs connect_to which is very intiutive)

Also for the example I would put:
```c++
settings.Set("name", "my_solver");
settings.Set("connect_to", "other_solver");
```

**Comment by philbucher** [comment]
I agree that `name` is maybe not the most intuitive 
I couldn't come up with a better word for it though 😕 

any suggestions/ideas?

**Comment by pooyan-dadvand** [comment]
Maybe `solver_name` or `my_name`?

**Comment by philbucher** [comment]
I would like to avoid `solver` bcs the code using the CoSimIO is not necessarily a solver

`my_name` also sounds a bit weird

I think `name` is ok, since we also pass `version` in the same `Info`. I think if we document it well then `name` is ok

**Comment by philbucher** [comment]
Sleeping over it I will go with `name`

Will adapt the rest of the repo now

**Comment by pooyan-dadvand** [comment]
> I would like to avoid `solver` bcs the code using the CoSimIO is not necessarily a solver

This is not completely true, CoSimIO works with any program but we already have many interfaces like convergence criteria, remotes functions, etc that reflect a solver and how it works.

IMO, going too generic in this case may cause some loss of clarity of the code in normal (solver) uses

**Comment by philbucher** [comment]
ok then lets go with `solver_name` ok?

This can (and has been!) be discussed until eternity, I don't have that strong opinion to defend anything else... :D

(Background: Roland is pushing me to use CoSim not only for "classical" solvers but also for other components such as Neural Networks)

**Comment by pooyan-dadvand** [comment]
You are right! It is very subjective and I see also the point of view of Roland and for the same reason I was proposing `my_name`. (Which you didn't like either) 

To be honest I don't have a strong opinion either...

**Comment by philbucher** [comment]
@pooyan-dadvand can you please check my latest commit? There I started to update the C-tutorials

The important take-away is that the `Info` that is returned from `CoSimIO::Connect` contains the name of the connection (`connection_name`)
=> as seen in my last commit this will have to be used in further calls to the CoSimIO

Do you agree?
If it is unclear we should speak as this is important

**Review by pooyan-dadvand — APPROVED** [review]
I don't have any better suggestion for the names. So I would approve it as it is already in a very good shape.

**Comment by pooyan-dadvand** [comment]
About the connection name in Info, I think it is a good idea. But I would also add the other name and connect to fields to it just for completeness.

**Comment by philbucher** [comment]
I will finish this soon, I am currently wroking from the inside out, i.e. I am updating the internals first and last I will come to the outermost interface layer

**Comment by philbucher** [comment]
@pooyan-dadvand this is a big chuck of improvements
The only larger update missing now is to use the `CoSimIO::ModelPart` instead of the raw arrays in the Interface
after that there are only some minor things left before we can have our second release :D

**Comment by pooyan-dadvand** [comment]
Please don't forget to update the tutorials readmes

**Comment by philbucher** [comment]
sure, there are anyway a lot of updates to be made

**Pull request merged**
