### PR TITLE
Switch testing to doctest

### PR DESCRIPTION
**Pull request by philbucher**
This PR replaces the `catch` library with the [`doctest`](https://github.com/onqtam/doctest) library
Quite minor changes are necessary as doctest stems from catch

=> I am doing this as doctest promises to compile and run faster and essentially has the same capabilities as catch

In some basic tests it was > 50% faster! (compile times)

Plus I would like to play with different testing frameworks to gather some experiences what might be also interesting for Kratos, and I think the CoSimIO is a good place to do this

FYI @loumalouomega

### CODE REVIEW

**Comment by loumalouomega** [comment]
I got in my experience reductions up to 70%, probably in Kratos will be greater as it uses exceptions which are quite expensive in compilation time.

**Comment by philbucher** [comment]
I think one can even disable the exceptions to further speed it up

**Comment by philbucher** [comment]
https://github.com/onqtam/doctest/blob/master/doc/markdown/configuration.md#doctest_config_super_fast_asserts

**Comment by philbucher** [comment]
@loumalouomega I checked your branch but you didn't change any macros
how did you measure the reduction?

**Comment by loumalouomega** [comment]
> @loumalouomega I checked your branch but you didn't change any macros
> how did you measure the reduction?

In a different code, not Kratos

**Comment by philbucher** [comment]
ah ok

playing around with it I think it is quite cool
=> has so many features already included that we could just use

I will bring it up, we are anyway going to transition to CTest in the long run

**Comment by loumalouomega** [comment]
> ah ok
> 
> playing around with it I think it is quite cool
> => has so many features already included that we could just use
> 
> I will bring it up, we are anyway going to transition to CTest in the long run

Doctest does not conflict with Ctest, I use them together in my current projects

**Comment by loumalouomega** [comment]
The thing is in order to ad tests to CTest must be known the tests in compilation time (actually CMake pahse before build). So one option could be to do a second build round and add the tests after the install

**Comment by philbucher** [comment]
This repo (and I think also AMatrix) does this

IMO it is pretty straight forward but probably the devil is in the details

**Comment by philbucher** [comment]
@loumalouomega I saw that in Kratos you added the header-source separated version right?
How did you use it? I didn't find this in the docs

**Comment by loumalouomega** [comment]
I haven't finished implementation yep, but there two options, adding to the rest of the sources of the Core or compile a library and link it to the Core

**Comment by philbucher** [comment]
did you find this in the docs?

**Comment by loumalouomega** [comment]
> did you find this in the docs?

Nope, it is quite standard way to proceed with external libs

**Comment by philbucher** [comment]
ok thx

**Pull request merged**
