### PR TITLE
using python 3.8 in CI

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by philbucher** [comment]
@pooyan-dadvand it seems there was an internal update to python 3.8 in the runners
Now the CI should works again

what do you think, should we test with several python versions (aka matrix build) ?

**Comment by pooyan-dadvand** [comment]
> @pooyan-dadvand it seems there was an internal update to python 3.8 in the runners
> Now the CI should works again
> 
> what do you think, should we test with several python versions (aka matrix build) ?

It would be useful. What is the effort to do that?

**Comment by philbucher** [comment]
> > @pooyan-dadvand it seems there was an internal update to python 3.8 in the runners
> > Now the CI should works again
> > what do you think, should we test with several python versions (aka matrix build) ?
> 
> It would be useful. What is the effort to do that?

close to nothing (in theory :smile:)
see [here](https://github.com/philbucher/KratosSalomePlugin/blob/master/.github/workflows/ci.yml#L26-L28)

I will add it to the todo list

**Comment by philbucher** [comment]
see #86

**Pull request merged**
