### PR TITLE
Adding new fortran wrapper for CoSimIO

### PR DESCRIPTION
**Pull request by Ankit-Nanda-altair**
Fortran Interface for:
- co_sim_io_c.h
- co_sim_io_c_info.h
- co_sim_io_c_model_part.h
New fuctions:
- CoSimIO_Info_GetString_Wrapper: wrapper for CoSimIO_Info_GetString()
- CoSimIO_ModelPart_Name_Wrapper: wrapper for CoSimIO_ModelPart_Name()

### CODE REVIEW

**Comment by philbucher** [comment]
wow awesome thanks!

I will review in the next days

Could you please add a basic test, e.g. for connection, like [this one](https://github.com/KratosMultiphysics/CoSimIO/blob/master/tests/integration_tutorials/c/connect_disconnect_a.c)

**Comment by Ankit-Nanda-altair** [comment]
Hi,

I have added a simple connect disconnect test for the fortran wrapper, however I could not test it on my machine as I need to associate the cosimio dll to the project and have a hard time associating it in visual studio. 

Please check the test and let me know if it worked for you or any errors it is showing

The connect disconnect test is in test\co_sim_io\fortran\connect_disconnect.f90

**Comment by Ankit-Nanda-altair** [comment]
Hi @philbucher ,

Do you have any idea why intel mpi checks are failing because I have not changed that part.

**Comment by philbucher** [comment]
sometimes the tests can fail, especially if MPI is involved
I restarted the job, hopefully it works now

**Comment by Ankit-Nanda-altair** [comment]
Thanks @philbucher , Seams it worked this time!

**Comment by philbucher** [comment]
Awesome, then lets go ahead :)
Thanks a lot for your contribution!

**Pull request merged**
