### PR TITLE
Add version

### PR DESCRIPTION
**Pull request by philbucher**
This adds the Version, pretty similar to how it is done in Kratos
two questions:
- would you prefer to have this more accessible? I.e. in the `CoSimIO` namespace and not in the `CoSimIO::Internals` namespace?
- would you prefer to have the version as `#define` like it is done in Kratos?

Only thing I am not sure yet is how to generate the hash yet (bcs it is header-only), but this can most likely be done by an actions after every merge
I would not do this atm, IMO it is not that important for now

### CODE REVIEW

**Comment by philbucher** [comment]
btw I made it matching to your tutotial

**Comment by pooyan-dadvand** [comment]
Thanks!

**Comment by pooyan-dadvand** [comment]
For the patch you may use cmake to create it getting the git hash if is a clone repo like in Kratos

**Comment by philbucher** [comment]
> For the patch you may use cmake to create it getting the git hash if is a clone repo like in Kratos

for C++ which is header only we don't need any CMake

Otherwise I agree this is the way how it should be done

**Pull request merged**
