### PR TITLE
Improve CO_SIM_IO_ERROR

### PR DESCRIPTION
**Pull request by philbucher**
now works same way as the `KRATOS_ERROR`

### CODE REVIEW

**Comment by philbucher** [comment]
FYI @pooyan-dadvand this improves the Exceptions in the CoSimIO
I created a simplified version of `Kratos::Exception` such that it works in the same way

I will wait with merging until I continue working on CoSimIO in the next days, in case you want to have a look

**Comment by pooyan-dadvand** [comment]
So in Kratos, it works with the one of the Kratos?

**Comment by philbucher** [comment]
Yes
If the macro is defined from outside (like we do when included CoSimIO in Kratos) the that one is used
The internal one is only used in case nothing was provided from outside

**Comment by philbucher** [comment]
@pooyan-dadvand this is how it works with Kratos:
https://github.com/KratosMultiphysics/Kratos/blob/c215507bf2e7bc3be9402f6ced8942952eb170a1/applications/CoSimulationApplication/custom_python/add_co_sim_io_to_python.cpp#L23-L32

**Pull request merged**
