### PR TITLE
Fix code loc win

### LINKED ISSUE #350: Bug in code location
I found out that the CodeLocation implementation fails in windows with an exception and causes exception within another exception situation which won't show the result.

The problem is in using [return fs::canonical(fs::path(GetFileName())).lexically_relative(fs::absolute(".")).string();](https://github.com/KratosMultiphysics/CoSimIO/blob/a5abb50a6910d6eb2af5788307c8d9949cd884e8/co_sim_io/sources/code_location.cpp#L24) 

And replacing it with the manual implementation in [Kratos](https://github.com/KratosMultiphysics/Kratos/blob/c1d9b2e30b557612aa379acfa2e16298523731a8/kratos/sources/code_location.cpp#L46) just solved the problem.

@philbucher It would be great if we you could create a release with this fix.

### PR DESCRIPTION
**Pull request by philbucher**
fixes #350

FYI @loumalouomega this is a slightly improved version of #351, including a test

### CODE REVIEW

**Comment by loumalouomega** [comment]
Huuuuum, test failing

**Comment by philbucher** [comment]
Why is it always windows 🙈
At least we are narrowing down the problem 

Interesting to see the differences, in particular of the function name macro.
In linux the namespace is added too, does not seem to be the case in windows

**Comment by loumalouomega** [comment]
> Why is it always windows 🙈 At least we are narrowing down the problem
> 
> Interesting to see the differences, in particular of the function name macro. In linux the namespace is added too, does not seem to be the case in windows

And the intel CI is still failing

**Comment by philbucher** [comment]
I am pretty sure I found the actual cause of the problem, I think I can fix it tonight

**Comment by philbucher** [comment]
merging now, the CI failures are unrelated

FYI @pooyan-dadvand the real source of the error was that there were some bugs in the filesystem implementation that we use, in particular the `fs::canonicial` implementation.
These have been fixed in the meantime, I updated the lib now

Can you please try if it fixes the issues?

**Pull request merged**
