### PR TITLE
Save&Load for DataContainer & ModelPart

### PR DESCRIPTION
**Pull request by philbucher**
This adds serialization for `DataContainer` & `ModelPart`

Esp for the `ModelPart` I think we will get back to again later when we switch to Intrusive pointers

very interesting: https://isocpp.org/wiki/faq/serialization

### CODE REVIEW

**Comment by philbucher** [comment]
@pooyan-dadvand what is also very interesting for the future and actually quite easy to realize is the exchange of arbitrary data
I can add that if you agree

=> as long as whatever the user gives has a default CTor as well as a `Save` and `Load` method we can exchange anything

**Comment by pooyan-dadvand** [comment]
IMO it is ok for now and in the future we may easily import the Kratos one here as it has few dependency to the rest of the Kratos

Nevertheless, I would switch to binary (at least in release mode) to improve the performance and more important, to keep the accuracy of the data without loss in the conversion to and form ascii.

**Comment by philbucher** [comment]
also to add that for arbitrary data we can use SFINAE to check if `Save` / `Load` are available and if not try to e.g. use the Serializer (that will most probably come in the future)

**Comment by philbucher** [comment]
closing as no longer needed

The functionalities have been added by using the `Serializer`

**Pull request closed without merging**
