### PR TITLE
Several updates

### PR DESCRIPTION
**Pull request by philbucher**
- Use only python versions that are non EOL (3.8-3.11)
- properly disable C-MPI tests, since there are only dummies that cause issues
- Update ASIO and pybind to latest versions
- add changelog for v4.3
- use newer CentOS image in CI (same as is used in Kratos)

### CODE REVIEW

**Comment by philbucher** [comment]
FYI @matekelemen I think you were asking about python 3.11 support some time ago

**Comment by philbucher** [comment]
FYI @loumalouomega now CoSimIO is back up to date

**Comment by loumalouomega** [comment]
:)

**Comment by matekelemen** [comment]
@philbucher thx!
plz tag me when you update CoSimIO in Kratos too.

**Pull request merged**
